name: Deploy Lambda

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          mkdir -p package
          python -m pip install -r requirements.txt --target ./package

      - name: Package Lambda function
        run: |
          cp lambda_function.py package/
          cd package
          zip -r ../lambda.zip .
          cd ..


      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          S3_BUCKET:    breez-nodeless-payment
          ZIP_FILE: lambda.zip
        run: |
          aws s3 cp $ZIP_FILE s3://$S3_BUCKET/$ZIP_FILE


